### ISSUE TITLE
获取二手房数据跑不成功

### ISSUE THREAD

**Issue by LeoZeda** [jumper2014/lianjia-spider#3]
![default](https://user-images.githubusercontent.com/8565999/38871583-e09efd64-4283-11e8-9f8a-55a9411ae0c9.png)
跑了一会进程直接挂了

**Comment by jumper2014** [comment]
1. 你线程池里面线程数多少？
2. 建议一边跑，一边ping下lianjia.com，先排除网络连接不好的情况。

**Comment by LeoZeda** [comment]
线程数是默认的，/lib/const/spider.py 这里定义是50
网络也没问题，城市各板块信息已经拿到了，成功抓了一两个区的数据

**Comment by jumper2014** [comment]
跑哪个城市的数据出现的问题？

**Comment by LeoZeda** [comment]
广州的

**Comment by LeoZeda** [comment]
可能是虚拟机的性能问题，调小线程数就好了
